name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy flake8

      - name: Lint (flake8)
        run: flake8 .

      - name: Type check (mypy)
        run: mypy .

      - name: Run tests (pytest)
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Upload MLflow artifacts (if any)
        if: success() && env.MLFLOW_TRACKING_URI != ''
        run: |
          # Example: download the latest email.txt artifact
          mlflow artifacts download --run-id $(mlflow run-id) --artifact-path email.txt

